version: '3.4'
services:
  dispatch:
    container_name: dispatch
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - PORT=9000
    ports:
      - 9000:9000
    restart: always
  client:
    container_name: client
    build:
      context: ./react-client
      dockerfile: Dockerfile.client
    environment:
      - NODE_ENV=dev
      - REACT_APP_RPC_HOST=dispatch
      - REACT_APP_SSE_HOST=dispatch
    ports:
      - 8080:80
    restart: always